services:

  app:
    build:
      context: .
      dockerfile: ./setup/docker/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
    networks:
      - local-bridge

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./setup/docker/nginx/:/etc/nginx/conf.d/
    networks:
      - local-bridge

networks:
  local-bridge:
    driver: bridge
